parameters:
#    yamei_rec_eye.example.class: Yamei\RecEyeBundle\Example

#services:
#    yamei_rec_eye.example:
#        class: %yamei_rec_eye.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    parse_file:
        class: Yamei\RecEyeBundle\Controller\RecEyeController
        calls:
        - [setContainer, [@service_container]]
